### ISSUE TITLE
Changefeed Cursor.Next() invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by onufert** [rethinkdb/rethinkdb-go#269] opened 2016-01-29 17:46 UTC
I've seen this panic a couple times now inside cursor.go @line 211 when closing a changefeed. It's not repeatable everytime, but usually about 1 in 5 times in our code it panics. 

```
server_1       | panic: runtime error: invalid memory address or nil pointer dereference
server_1       | [signal 0xb code=0x1 addr=0x20 pc=0x56eb9f]
server_1       |
server_1       | goroutine 11581 [running]:
server_1       | github.com/dancannon/gorethink.(*Cursor).loadNextLocked(0xc820683ef0, 0x7c4520, 0xc8205d8600, 0x1, 0x0, 0x0)
server_1       |   /opt/go/src/bitbucket.org/X/server/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:211 +0x41f
server_1       | github.com/dancannon/gorethink.(*Cursor).Next(0xc820683ef0, 0x7c4520, 0xc8205d8600, 0x1)
server_1       |   /opt/go/src/bitbucket.org/X/server/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:166 +0x91
server_1       | bitbucket.org/X/server/F.monitorChangeFeed.func1(0xc820683ef0, 0xc8205176e0)
server_1       |   /opt/go/src/bitbucket.org/X/server/F/f_db.go:33 +0x6d
server_1       | created by bitbucket.org/X/server/F.monitorChangeFeed
server_1       |   /opt/go/src/bitbucket.org/X/server/F/f_db.go:41 +0x5d
```

There's a few different goroutines running and the close on the cursor occurs after a chain of signals propagate. Below is an example of the code that exercises this bug:

``` go
func ... {
    feed, sig, err := dbConsumer.GetDocChangeFeed(id)
    if err != nil {
        return
    }
    defer func () {close(sig)}()
   for flag {
          select {
            case doc := <-feed:
                ....
         }
       }
       ...
       return
}

//GetDocChangeFeed ...
func (d *RethinkDBConsumer) GetDocChangeFeed(id string) (<-chan FeedMsg, chan<- bool, error) {
    sig := make(chan bool)
    res, err := r.DB(d.dbName).Table(d.dbTable).Get(id).Changes(r.ChangesOpts{IncludeInitial: true}).Run(d.session)
    if err != nil {
        return nil, nil, err
    }
    ch := make(chan FeedMsg)

    go func() {
        var value interface{}
        for res.Next(&value) {
            ...  
                        ch <- FeedMsg{....}
        }
        close(ch)
    }()

    //Monitor for unsubscribe
    go func() {
        <-sig
        res.Close()
    }()

    return ch, sig, nil
}

```

Reviewing cursor.go, pretty sure the panic is because c.conn is nil, which c.Close() sets to nil.

But if c.Close() is setting that to nil, then I don't see how loadNextLocked is called. You've got the mutex around that function and the proper checks for c.closed. 

It is possible if c.conn.Conn is nil then c.Close could return without ever setting the closed flag (line 117).
But I'm 99.9% my code isn't calling disconnect on the session. That only happens if my server exits its main loop, which is in a forever loop. 

The only other place where I can see a possible hole are lines 193-195, where c.fetchMore() is called. The mutex is released, which the c.Close() could be executed, and then c.fetchMore() returns and we get the panic. This should prevent this:

``` go
        if len(c.buffer) == 0 && len(c.responses) == 0 && !c.finished {
            c.mu.Unlock()
            err := c.fetchMore()
            c.mu.Lock()
            if err != nil || c.closed {
                return false, err
            }
        }
```

**Comment by gthmac** [comment] 2016-01-29 18:45
Same here, very reproducable in fact.

```
*****
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x5592df]

goroutine 62 [running]:
github.com/dancannon/gorethink.(*Cursor).loadNextLocked(0xc82045e6e0, 0x9bb8c0, 0xc8202da280, 0xc8202da280, 0x0, 0x0)
        /home/centos/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:211 +0x41f
github.com/dancannon/gorethink.(*Cursor).Next(0xc82045e6e0, 0x9bb8c0, 0xc8202da280, 0x9bb8c0)
        /home/centos/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:166 +0x91
github.com/dancannon/gorethink.(*Cursor).Listen.func1(0x9db4e0, 0xc82047f800, 0xc82045e6e0)
        /home/centos/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:352 +0x19d
created by github.com/dancannon/gorethink.(*Cursor).Listen
        /home/centos/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:361 +0x49
*****
```

Here is the code snippet by the way that causes all the issues with the panic-triggering code commented out (just FYI as seeing it might trigger eventually something :-) ):

```
...
    // do we need to wait for the result?
    if actionEntry.Wait {
        /*
            mychan := make(chan events.DocChange)
            // start the changeFeed from DB
            cursor, dberr := r.Table(t.EventTable).Get(id).Changes().Run(cfg.EventDB)
            if dberr != nil {
                errmsg := fmt.Sprintf("%+v", dberr)
                cilog.Log(sys.ERROR, cierrors.LogError(&API_ERR_DB_GET, errmsg))
                replyWithError(c, &API_ERR_DB_GET)
                return
            }
            cursor.Listen(mychan)
            defer cursor.Close()

            var change events.DocChange
        */

        var res t.VEvent
        for done := false; !done; {
            select {
            /*
                case change = <-mychan:
                    _ = change
            */
            case <-time.After(time.Duration(10) * time.Millisecond):
                _ = done
            }
            resp, dberr := r.Table(t.EventTable).Get(id).Run(cfg.EventDB)
            if dberr != nil {
                errmsg := fmt.Sprintf("%+v", dberr)
                cilog.Log(sys.ERROR, cierrors.LogError(&API_ERR_DB_GET, errmsg))
                replyWithError(c, &API_ERR_DB_GET)
                return
            }
            defer resp.Close()
            if resp.IsNil() {
                continue
            }
            dberr = resp.One(&res)
            if dberr != nil {
                errmsg := fmt.Sprintf("%+v", dberr)
                cilog.Log(sys.ERROR, cierrors.LogError(&API_ERR_DB_GET, errmsg))
                replyWithError(c, &API_ERR_DB_GET)
                return
            }
            if res.Status != string(events.EventClosed) {
                continue
            }
            done = true

        }
....
```

**Comment by dancannon** [comment] 2016-01-29 19:23
I will try to look into this over the weekend, but if somebody could submit a pr I would really appreciate it.

Thanks for the detailed bug report!

**Comment by dancannon** [comment] 2016-01-30 15:44
@onufert I think your assessment was correct, I updated the cursor to check if it is closed after fetching more results in the [fix-cursor-panic](https://github.com/dancannon/gorethink/compare/fix-cursor-panic) branch, if you could both check your code with this branch to see if it has fixed the issue that would be great.

FYI the reason that the cursor is unlocked when fetching results is that I didnt want to block the cursor during any network requests, especially when using changefeeds which might block for a significant amount of time. However this is obviously causing issues now :)

**Comment by onufert** [comment] 2016-02-01 14:30
@dancannon Thank you for looking over it this weekend! Greatly appreciate the help. I'm going to run our production code this week with the changes and cofirm we don't see the panic anymore. Pretty confident this will work.

**Comment by gthmac** [comment] 2016-02-01 16:30
@dancannon Have been running the bug fixed code for half a day now without any issues. Seems solved to me.

Once again, Dan, I very much appreciate your fast response and professional attitude. Awesome, indeed.

**Comment by dancannon** [comment] 2016-02-01 17:45
Thanks to both of your for your help. I will release a version later this evening.

**Comment by dancannon** [comment] 2016-02-01 22:26
Merged to master.

**Closed as completed** 2016-02-18 19:20 UTC
Labels: t:bug, p:high
