### ISSUE TITLE
Can't 'go get' this package

### ISSUE THREAD

**Issue by nabaragpaul** [rethinkdb/rethinkdb-go#410] opened 2017-04-16 20:51 UTC
go get is failed to download this package .

I have set GOPATH correctly and tried "go get" with github link and -insecure mode also but no luck
Is there anything i am missing ?

**Comment by thewraven** [comment] 2017-05-16 13:56
Have you already solved the issue by yourself? If not, can you be more specific about what is the error or problem you see?

I've just tried with the following commads:

[setup a clean gopath]
```
mkdir ~/gorethink
export GOPATH=~/gorethink
```
[Go get the last version of the package]

`go get -u -v github.com/GoRethink/gorethink`
With the -v flag you will see what go is downloading and if something fails, it will tell you.

**Comment by xeger** [comment] 2017-05-18 15:59
GoRethink is intended to be distributed through `gopkg.in` which provides semantic versioning. Therefore, you want to refer to it by its canonical import path:

```
go get gopkg.in/gorethink/gorethink.v2
```

You also want to use that path when you `import` it in your golang source files.

**Comment by romerojunior** [comment] 2017-07-05 15:17
I'm also experiencing the same issue, the command below just hangs:

`go get gopkg.in/gorethink/gorethink.v3`

gdm also breaks during the compilation of influxdata/telegraf due to its dependency on gorethink.v3.

Any advice?

**Comment by xeger** [comment] 2017-07-09 16:27
Sorry to hear that you're having `go get` issues; it works well for me with `go1.8.3 darwin/amd64` and `git version 2.11.0 (Apple Git-81)`.

I'm not a huge fan of the `gopkg.in` distribution model myself, so I'm not terribly sure how to troubleshoot. I suppose you could begin by looking at a process tree to determine what's hung; a likely scenario is that `go get`'s invocation of `git` is hanging because the git client is prompting for input unexpectedly.

I can offer you two workarounds. The simplest is to clone the repository yourself, without relying on `gopkg.in` or `go get`:

```bash
cd $GOPATH/src
mkdir -p gopkg.in/gorethink
cd gopkg.in/gorethink
git clone https://github.com/gorethink/gorethink gorethink.v3
```

This preserves the import naming structure, and invoking git directly might give you a hint about what's hanging.

The other workaround is to use a tool like `Glide` or `dep` to manage the dependencies of your project. (This only works if you're the author of the project and you can commit against it.) In this case you can ask your dependency tool to explicitly clone from GitHub, and even to use a specific branch.

**Comment by thewraven** [comment] 2017-07-09 21:20
@romerojunior Can you specify which OS, go and git version that are you using?  What is the output of:

```
go get -v -u gopkg.in/gorethink/gorethink.v3
```


_Sent from my Motorola Moto G4 Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by romerojunior** [comment] 2017-07-10 13:44
Did as @xeger described and it worked (cloning the repo and preserving the naming structure).

Nevertheless, here is the information you requested: 

Running on **CentOS release 6.9 (Final)**, with git version 1.7.1 and go version go1.8.3 linux/amd64.

The output of **go get -v -u gopkg.in/gorethink/gorethink.v3**:

```
[root@xxx ~]# go get -u -v gopkg.in/gorethink/gorethink.v3
Fetching https://gopkg.in/gorethink/gorethink.v3?go-get=1
Parsing meta tags from https://gopkg.in/gorethink/gorethink.v3?go-get=1 (status code 200)
get "gopkg.in/gorethink/gorethink.v3": found meta tag main.metaImport{Prefix:"gopkg.in/gorethink/gorethink.v3", VCS:"git", RepoRoot:"https://gopkg.in/gorethink/gorethink.v3"} at https://gopkg.in/gorethink/gorethink.v3?go-get=1
gopkg.in/gorethink/gorethink.v3 (download)
### [hangs...] 
```

Edit:

From my laptop **macOS 10.12.5 (16F73) Kernel Version: Darwin 16.6.0**, running **go version go1.8.3 darwin/amd64** and **git version 2.11.0 (Apple Git-81)** it worked like a charm, without the need for any workaround!

**Comment by thewraven** [comment] 2017-07-10 14:04
Thanks @romerojunior I was able to reproduce your issue. Seems like problem came from the gopkg.in service, and the suggested git version to use with gopkg.in must be >= 1.7.3.4.

Here's the [original issue](https://github.com/niemeyer/gopkg/issues/36) that describes the problem.

**Comment by xeger** [comment] 2017-07-14 16:34
@dancannon based on @thewraven's research, I think we can close this one as "not related to gorethink" -- it's a compatibility issue 'twixt gopkg.in and git < 1.7.4

**Closed as completed** 2017-07-15 21:04 UTC
Labels: t:bug, s:help-wanted
