### ISSUE TITLE
Bug when updating time.Time in a nested map

### ISSUE THREAD

**Issue by or-else** [rethinkdb/rethinkdb-go#231] opened 2015-09-23 01:43 UTC
The driver loses type information from a nested map:

```
when := time.Now()
rdb.DB("test_db").Table("test_table").Get(id).
  Update(
    map[string]map[string]time.Time{
      "LastSeen": map[string]time.Time{"some_tag": when}}
  ).RunWrite(a.conn)
```

The time ends up being updated as a string type instead of the expected `{'$reql_type$': 'TIME'}` type.

**Comment by or-else** [comment] 2015-09-24 00:42
I went to golang-nuts with a question on how to fix this, #201, and all similar problems once and for all:
https://groups.google.com/forum/#!topic/golang-nuts/T_FbJGz_kQ0

What @ugorji has suggested will work. It will also allow to reduce the amount of code in gorethink by a lot.

**Comment by kofalt** [comment] 2015-09-24 05:28
FWIW, :+1: to the [github.com/ugorji/go/codec](https://github.com/ugorji/go/tree/master/codec#codec) package.
I've both read a lot of the documentation and seen it used to great effect before. Quality code.

No current comment on its possible use for gorethink; I'm comfortable letting @dancannon sort that out.
If that's a desired change, might be a separate & larger ticket.

**Comment by dancannon** [comment] 2015-09-24 08:57
Hmm very interesting, thanks for posting this. I will definitely look into seeing if this can replace the encoding package.

That being said I will probably fix this bug first with the current encoding package and look into moving to the new package later on.

**Comment by or-else** [comment] 2015-09-24 17:32
Here is another bug with the same root cause:

Define a custom type `type Aa int`
Define stringer and json.Marshaller for it:

```
func (Aa) String() string {
   return "bug!"
}

func (Aa) MarshalJSON...
...
```

Now, if you insert Aa type in a map[string]Aa{"aaVal": 123}, everything works as expected, string "bug!" is inserted. If you insert Aa type as a part of a struct{AaVal: Aa(123)} , 123 is inserted.

**Comment by dancannon** [comment] 2015-09-28 20:43
So I have had a go at fixing these issues however I could not replicate any of the issues. Well sort of, GoRethink does not currently support "MarshalJSON" so `123` is the expected behaviour. In fact I am not sure how you ever got `bug!`.

If you could provide anymore information such as your version of GoRethink or a full program which shows the issue I would really appreciate that. That being said as mentioned I will look into moving to go-codec so it may not be an issue for long.

**Comment by or-else** [comment] 2015-09-28 21:46
Sure, I'll produce a minimal demo in the next couple of days.

**Comment by or-else** [comment] 2015-09-28 21:48
As for `"bug!"` vs `123`, the bug is inconsistency of it. The result should be the same regardless of how it's inserted, in a map or in a struct.

**Comment by dancannon** [comment] 2015-09-28 22:10
Completely agree I just couldn't replicate it.

**Comment by or-else** [comment] 2015-09-28 22:42
For the first bug:

```
package main

import (
    rdb "github.com/dancannon/gorethink"
    "log"
    "time"
)

type OuterStruct struct {
    OuterField string
    Nested     InnerStruct
}

type InnerStruct struct {
    InnerField1 time.Time
    InnerField2 time.Time
}

func main() {
    session, err := rdb.Connect(rdb.ConnectOpts{Address: "localhost:28015"})
    if err != nil {
        log.Fatalln(err.Error())
    }
    rdb.DBDrop("test_db").RunWrite(session)
    rdb.DBCreate("test_db").RunWrite(session)
    rdb.DB("test_db").TableCreate("test").RunWrite(session)

    rdb.DB("test_db").Table("test").Insert(&OuterStruct{
        OuterField: "outer",
        Nested: InnerStruct{
            InnerField1: time.Date(2010, 1, 2, 3, 4, 5, 6, time.UTC),
            InnerField2: time.Date(2010, 2, 3, 4, 5, 6, 7, time.UTC),
        }}).RunWrite(session)

    when := time.Now()
    rdb.DB("test_db").Table("test").Update(map[string]map[string]time.Time{"Nested": map[string]time.Time{"InnerField1": when}}).RunWrite(session)
}
```

The DB now contains:

```
{
"Nested": {
"InnerField1":  "2015-09-28T15:40:33.687653477-07:00" ,
"InnerField2": Wed Feb 03 2010 04:05:06 GMT+00:00
} ,
"OuterField":  "outer" ,
"id":  "96ebdb83-5706-40a0-a59b-970d90814145"
}
```

`InnerField1` is string, `InnerField2` is timestamp

**Comment by or-else** [comment] 2015-09-30 01:14
Here is the minimum demo for the other bug:

```
package main

import (
    rdb "github.com/dancannon/gorethink"
    "log"
)

type Custom int

func (*Custom) MarshalJSON() ([]byte, error) {
    return []byte(`"MarshalJSON"`), nil
}

type Nested struct {
    Test CustomStruct
}

type CustomStruct struct {
    InStruct *Custom
}

func main() {
    session, err := rdb.Connect(rdb.ConnectOpts{Address: "localhost:28015"})
    if err != nil {
        log.Fatalln(err.Error())
    }
    rdb.DBDrop("test_db").RunWrite(session)
    rdb.DBCreate("test_db").RunWrite(session)
    rdb.DB("test_db").TableCreate("test").RunWrite(session)

    var val Custom = 123
    rdb.DB("test_db").Table("test").Insert(&Nested{
        Test: CustomStruct{InStruct: &val}}).RunWrite(session)
    rdb.DB("test_db").Table("test").Insert(
        map[string]interface{}{"Test": map[string]*Custom{"InMap": &val}}).RunWrite(session)

}
```

Database content:

```
{
"Test": {
"InStruct": 123
} ,
"id":  "238ec452-75b5-4455-9e53-c5fdb7647f5e"
} {
"Test": {
"InMap":  "MarshalJSON"
} ,
"id":  "ef14fb39-5600-4939-92a2-8d4b8a80469d"
}
```

**Comment by dancannon** [comment] 2015-09-30 20:26
I am now very confused, here is my output for each test. Would anybody else be able to give these scripts a test and see if they get the correct result?

I am using GoRethink v1.1.3 with RethinkDB 2.1

1:

``` json
[
  {
    "Nested": {
      "InnerField1": {
        "$reql_type$": "TIME",
        "epoch_time": 1443644436.255,
        "timezone": "+01:00"
      },
      "InnerField2": {
        "$reql_type$": "TIME",
        "epoch_time": 1265169906,
        "timezone": "+00:00"
      }
    },
    "OuterField": "outer",
    "id": "2f41dcb4-25d6-4a5e-b6d3-b4eaae1b0613"
  }
]
```

2: 

``` json
[
  {
    "Test": {
      "InStruct": 123
    },
    "id": "906cfab8-8722-4b21-be91-1f0f8889db27"
  },
  {
    "Test": {
      "InMap": 123
    },
    "id": "792c3536-db4b-4ffb-9d75-a5e8bdfbea12"
  }
]
```

**Comment by or-else** [comment] 2015-09-30 20:28
I'll update everything to the latest version and try again. Maybe it's version-dependent.

**Comment by or-else** [comment] 2015-09-30 20:40
Yes, updating to the latest version of gorethink fixed the problem. All good, thanks. I had a version from a month ago.

**Comment by dancannon** [comment] 2015-09-30 20:41
Huh, well I guess that's good! Thanks.

**Closed as completed by dancannon** 2015-09-30 20:41 UTC
Labels: t:bug, p:medium

**Comment by dancannon** [comment] 2015-10-25 13:20
Just thought I would report back here with some of my results after looking into switching to go-codec. In my tests I noticed that go-codec has some weird edge cases with embedded structs, I doubt this would cause issues for most people but I think it's worth pointing out.

Unfortunately I had some bigger issues with RethinkDB pseudo-types, unfortunately due to the way that the `GROUPED_DATA` type works it is not possible to create an extension for this type because unlike the other pseudo-types there is no single Go type that can represent the grouped data. That being said it seemed to work very well for the TIME and GEOMETRY pseudo-types.

I have not given up on getting rid of the multiple decoding steps in GoRethink but I don't think it will be so easy :)

**Comment by ugorji** [comment] 2015-10-25 13:35
Hi, @ugorji, author of go-codec here. Please raise issues that you find and I will try to fix ASAP. I like to pride myself on go-codec always working. The one caveat is when we can't do anything about it e.g. you embed a type which implements a known interface (eg binarymarshaler, textmarshaler, jsonunmarshaler) and so enclosing for automatically implements that interface.

**Comment by dancannon** [comment] 2015-10-25 13:45
Hey @ugorji, I didnt mean to make it sound like go-codec was the issue here, I have used your library very successfully in other projects (thanks for the great library)! However I just don't think it will solve the issue here where we need to convert the database JSON to a generic map, convert any "pseudo-types" into the go equivalent and then finally unmarshal that into the users data structure.

Regarding the embedded types issue with go-codec I have been meaning to create an issue but I haven't had the time to properly replicate it, I will try to find some time this week.

By the way pseudo-types look a bit like this:

```
{'$reql_type$': 'TIME', 'timestamp': 123456789}
converted into
time.Time{}
```

```
{"$reql_type$":"GROUPED_DATA","data":[["Alice",4.5],["Bob",12.5]]}
converted into
[{"group":"Alice","reduction":4.5},{"group":"Bob","reduction":12.5}]
```

**Comment by or-else** [comment] 2015-10-25 19:09
Let's see if I understand the problem correctly. 

```
cur, _ := DB("db01").Table("test").Group("user").Run(session)
var res []UserStruct
cur.Next(&res)
```

You can't do 

```
type GorethinkGroupExt []map[string]interface{}

func (GorethinkGroupExt) ConvertExt(v interface{}) {
    return v
}

func (GorethinkGroupExt) UpdateExt(slice_of_UserStruct interface{}, json_GROUP_DATA interface{}) {
    // handle conversion from GROUP_DATA to []UserStruct
    ...
}

 sliceType := reflect.TypeOf([]interface{})
 var groupSlice GorethinkGroupExt
 h := new(codec.JsonHandle)
 h.SetInterfaceExt(sliceType, 1, groupSlice)
```

because it would affect reading to any slice, not just the slice which is a result of `group()`? Or is it something else?

**Comment by dancannon** [comment] 2015-10-25 19:16
My understanding is that you would need to create an extension for the type `[]UserData` which would make it pretty annoying having to preregister any user types.

If it is possible to do what you suggest then maybe using go-codec won't be so impossible. I'll try to test it out tomorrow.

**Comment by or-else** [comment] 2015-10-25 19:25
BTW, in my example `GorethinkGroupExt` can be just an empty struct{}. It's actual composition makes no difference because it's not used.

**Comment by dancannon** [comment] 2015-10-25 19:30
Ah yes in that case you were right. Also `[]interface{}` wouldn't match all slices since extensions require exact matches.

**Comment by or-else** [comment] 2015-10-25 20:22
Are you saying that in the example I gave `GorethinkGroupExt.UpdateExt` won't be called when the user attempts to unmarshal to `[]UserStruct`? @ugorji , do we miss anything here?

**Comment by ugorji** [comment] 2015-10-26 14:29
@or-else Yes, the extensions are called only when encountering a (named) type which had the extension registered i.e. user would have to register:

```
type UserStructList []UserStruct
type UserStructListExt struct {} // now add UpdateExt and ConvertExt on these
// now register this on the Handle
```

Since UserStruct is a custom type unknown explicitly to gorethink, there's no way I can think of to handle what you are trying to do (off the top of my head).

**Comment by or-else** [comment] 2015-10-26 17:31
OK, makes sense, thanks.

Here is another approach to consider. 

I believe (correct me if I'm wrong) GROUPED_DATA is only returned by `Group()` and `GroupByIndex()`. If so, you can treat it as a special case. You know when to expect GROUPED_DATA in results. You can register an extension for the concrete type without knowing ahead of time what type the user passed:

```
func test(x interface{}) {
  return reflect.TypeOf(x)
}
```

`test("hello")` will return type string, not type interface{}. All you need to do is unwrap 
`{"$reql_type$":"GROUPED_DATA","data":[["Alice",4.5],["Bob",12.5]]}` (b.t.w, are you sure it's an array of arrays?) to something like 

```
type GroupedData struct {
  Type string `json:"$reql_type$"`
  Data json.RawMessage `json:"data"`
}
```

Then do the usual unmarshaling of Data to user's object.

**Comment by dancannon** [comment] 2015-10-26 22:03
I think that would only work if you were using `Group` at the top level of your query, if you were using `Group` inside `Map` for example then you would not know what Go type should be a GroupedData type.

I also had a look at how the new Java driver works and it is doing the exact same as this driver https://github.com/rethinkdb/rethinkdb/blob/josh/java-driver/drivers/java/src/main/java/com/rethinkdb/net/Cursor.java#L161.

I will likely migrate the JSON codec from `encoding/json` to `go-codec` in the next release but I don't think we will be able to replace any of the `encoding` package.

Also thanks @ugorji for all the help.

**Comment by dancannon** [comment] 2015-11-08 14:32
Another attempt, although this requires the mapstructure library which I am not too keen to use since it has some slightly different behaviour.

``` go
package main

import (
    "fmt"
    "reflect"

    "github.com/davecgh/go-spew/spew"
    "github.com/mitchellh/mapstructure"
    "github.com/ugorji/go/codec"
)

type GroupedData struct {
    Data interface{}
}

type Groups []Group
type Group struct {
    Group     string
    Reduction float64
}

type GroupedDataExt struct{}

func (x GroupedDataExt) WriteExt(interface{}) []byte          { panic("unsupported") }
func (x GroupedDataExt) ReadExt(interface{}, []byte)          { panic("unsupported") }
func (x GroupedDataExt) ConvertExt(v interface{}) interface{} { panic("unsupported") }
func (x GroupedDataExt) UpdateExt(dest interface{}, v interface{}) {
    switch gd := dest.(type) {
    case GroupedData:
        switch obj := v.(type) {
        case map[interface{}]interface{}:
            reqlObjToGroupedData(obj, gd.Data)
        default:
            panic(fmt.Sprintf("unsupported format for time conversion: expecting int64/uint64; got %T", v))
        }
    case *GroupedData:
        switch obj := v.(type) {
        case map[interface{}]interface{}:
            reqlObjToGroupedData(obj, gd.Data)
        default:
            panic(fmt.Sprintf("unsupported format for time conversion: expecting int64/uint64; got %T", v))
        }
    default:
        panic(fmt.Sprintf("unsupported format for time conversion: expecting int64/uint64; got %T", v))
    }
}

func reqlObjToGroupedData(obj map[interface{}]interface{}, v interface{}) {
    if obj["$reql_type$"] == "GROUPED_DATA" {
        if data, ok := obj["data"]; ok {
            ret := []interface{}{}
            for _, v := range data.([]interface{}) {
                v := v.([]interface{})
                ret = append(ret, map[string]interface{}{
                    "group":     v[0],
                    "reduction": v[1],
                })
            }

            if err := mapstructure.Decode(ret, v); err != nil {
                panic(fmt.Sprintf("Error decoding pseudo-type GROUPED_DATA: %s", err))
            }
        } else {
            panic(fmt.Sprintf("pseudo-type GROUPED_DATA object %v does not have the expected field \"data\"", obj))
        }
    } else {
        panic(fmt.Sprintf("pseudo-type GROUPED_DATA object %v does not have the expected field \"$reql_type$\"", obj))
    }
}

func main() {
    s := `{"$reql_type$":"GROUPED_DATA","data":[["Alice",4.5],["Bob",12.5]]}`
    var groups []Group
    v := GroupedData{&groups}

    h := new(codec.JsonHandle)
    h.SetInterfaceExt(reflect.TypeOf(GroupedData{}), 1, GroupedDataExt{})

    dec := codec.NewDecoderBytes([]byte(s), h)
    err := dec.Decode(&v)

    spew.Dump(groups, err)
}
```

```
([]main.Group) (len=2 cap=2) {
 (main.Group) {
  Group: (string) (len=5) "Alice",
  Reduction: (float64) 4.5
 },
 (main.Group) {
  Group: (string) (len=3) "Bob",
  Reduction: (float64) 12.5
 }
}
(interface {}) <nil>
```

**Comment by or-else** [comment] 2015-11-11 19:21
Sorry for not responding earlier. I was travelling. 

I don't think I understand. Would not the same criticism apply here as you wrote in https://github.com/dancannon/gorethink/issues/231#issuecomment-151297386? If you know ahead of time that it's GROUPED_DATA than you surely can handle it, but you said you can't know if it's a `Group` inside a `Map`. What am I missing?

**Comment by dancannon** [comment] 2015-11-12 23:11
My attempt is slightly different as while you still need to know your data structure ahead of time it should support nested `Group` terms. 

Honestly I still think this is not a proper solution but it was pretty fun to play with go-codec.
