### ISSUE TITLE
Connection pool is exhausting connections, eventually hangs

### ISSUE THREAD

**Issue by oliver006** [rethinkdb/rethinkdb-go#171] opened 2015-04-07 13:01 UTC
After running my server for a while I start to see file descriptors being used up and when I dump goroutines I see tons of these:

```
goroutine 123981 [chan receive, 455 minutes]:
github.com/dancannon/gorethink.(*Pool).conn(0xc20805a1b0, 0x7bbf80, 0x0, 0x0)
        /home/web/apps/fbrss/src/github.com/dancannon/gorethink/pool.go:252 +0x2a2
github.com/dancannon/gorethink.(*Pool).query(0xc20805a1b0, 0xc200000001, 0x0, 0xc20834b720, 0xc208226420, 0x0, 0x0, 0x0)
        /home/web/apps/fbrss/src/github.com/dancannon/gorethink/pool.go:504 +0x40
github.com/dancannon/gorethink.(*Pool).Query(0xc20805a1b0, 0x1, 0x0, 0xc20834b720, 0xc208226420, 0x0, 0x0, 0x0)
        /home/web/apps/fbrss/src/github.com/dancannon/gorethink/pool.go:496 +0x94
github.com/dancannon/gorethink.Term.Run(0x92df70, 0x5, 0x4700000000, 0x0, 0x0, 0xc2081dfdd0, 0x2, 0x2, 0xc208226390, 0xc208010310, ...)
        /home/web/apps/fbrss/src/github.com/dancannon/gorethink/query.go:197 +0x10c
main.LoadUser(0xc20834b5ea, 0x28, 0x945b50, 0x6, 0xc208446d90, 0x0, 0x0)
        /home/web/apps/fbrss/data.go:235 +0xa75
main.feedHandler(0xc2080691e0)
        /home/web/apps/fbrss/feed.go:182 +0x1b4
```

(lines are off by one, 252 for me is https://github.com/dancannon/gorethink/blob/master/pool.go#L253)

Depending on how big I make the pool this starts happening after 30-90 minutes of running at 2-5 reqs/sec.
My code isn't doing anything extraordinary, looks roughly like this:

```
    rows, err = r.Table("users").GetAllByIndex("cookie", value).Limit(1).Run(rethinkSession)
    if err != nil {
        return nil, nil
    }
    var user User
    err = rows.One(&user)
    ...wrapping up....
```

Weird thing is, after I start the server it keeps opening more connections until the limit is reached and it runs fine at the limit for a while. Eventually, something triggers the build up of opening new connections and everything stalls.
Let me know if I can add anything else.

**Comment by dancannon** [comment] 2015-04-07 14:23
Thanks for reporting this issue, I have started investigating the cause of the issue and have a couple of questions:
- What pool settings are you using?
- Roughly how many concurrent queries are being executed?
- Would it be possible to run your code with some kind of logging on the `return nil, nil` line, its possible that the query is failing and then the connection is not being closed properly (I doubt this is actually whats happening but I would like to rule it out)

This issue has been popping up for a while but it is quite hard to debug so any extra information you might have would be great.

**Comment by dancannon** [comment] 2015-04-07 14:46
I think I might have spoken too soon regarding the call to `One` not properly closing the connection, I have just created a simple example which shows that the connection is not closed if the result is nil (although this might not be the same bug you are having...)

Could you please pull the hotfix/v0.6.4 branch and see if you are still seeing these issues?

**Comment by oliver006** [comment] 2015-04-07 14:55
Thanks, I'll try to set up a test later and will let you know if that helped. I think I have a good chunk of calls to `One()` that don't return a result so that could very well be it.
I'll update the issue when I have something.

**Comment by oliver006** [comment] 2015-04-07 19:20
I gave it a quick try on my local machine and it seems like this fixed it, nice work!

**Comment by oliver006** [comment] 2015-04-09 22:58
I ran your hotfix for ~24h now, the connection count holds steady so I guess that fixed it.

**Comment by dancannon** [comment] 2015-04-09 23:23
Brilliant, thanks for checking. Ill probably merge the fix tomorrow.

**Comment by dancannon** [comment] 2015-04-14 22:33
The fix has been merged to master, thanks again for reporting the bug.

**Comment by nkev** [comment] 2015-07-01 02:40
We have similar situation where any database access times out for any query after about a week. I'm using the current master driver and we've just found the SetVerbose(true) option and have set it to true for next time. Will report back here. How would I log the connection count in the pool? Any other tips for logging connection related info would be appreciated.

**Comment by dancannon** [comment] 2015-07-01 08:30
Hi @nkev, I am sorry to hear you are having this issue. Could you make sure that all `Cursor`s are being closed, if a cursor is not closed then the connection remains open. A `Cursor` is automatically closed if:
- A query is called with `RunWrite`
- A query is called with `Exec`
- A cursors results are fetched with `One`
- A cursors results are fetched with `All`

If you use any other method such as `Next` or `Listen` then the cursor will not be closed. If all cursors are correctly being closed then we can look into adding some more logging to the driver to try and debug this issue.

**Comment by dancannon** [comment] 2015-07-03 20:38
@nkev Any updates on this issue? If this is indeed an issue in the driver then it could be quite serious and I would like to fix it as soon as possible.

**Comment by nkev** [comment] 2015-07-04 00:31
Not yet Dan. We will examine the entire code on Monday for any methods that don't close the cursor, as per your instructions above. If there are any, I will report back here immediately. We've enabled the SetVerbose(true) option but we're not really seeing much info in the logs. Is there a way to log the connection count in the pool? Anything else we can log at driver level?

**Comment by dancannon** [comment] 2015-07-04 11:59
Ok great thanks, I have created a new branch called `feature/pool_debug_logging` which has more logging around acquiring and releasing connections. Hopefully that should help debugging.

**Comment by nkev** [comment] 2015-07-07 02:57
We've gone through the entire codebase and can  confirm we are not using anything that would leave an open cursor. Stephanie is now applying the `feature/pool_debug_logging` branch so we can hopefully get more insight into the issue. I'll report back here again.

**Comment by nkev** [comment] 2015-07-22 02:18
Is this the right way to close the cursor in the following query?

``` go
    _, err := rdb.Table("users").Get(UserID).Update(User).RunWrite(rdbSession)
    if err != nil {
        //log and exit function
    }
    defer rdb.Cursor.Close()
```

or is it always better to do this:

``` go
    cursor, err := rdb.Table("users").Get(UserID).Update(User).RunWrite(rdbSession)
    if err != nil {
        //log and exit function
    }
    defer cursor.Close()
```

**Comment by dancannon** [comment] 2015-07-22 08:42
The correct method is:

``` go
    cursor, err := rdb.Table("users").Get(UserID).Update(User).RunWrite(rdbSession)
    if err != nil {
        //log and exit function
    }
    defer cursor.Close()
```

**Comment by kofalt** [comment] 2015-07-22 17:28
@dancannon Sorry if I'm behind the times - I thought [`RunWrite`](https://godoc.org/github.com/dancannon/gorethink#Term.RunWrite) just returns a [`WriteResponse`](https://godoc.org/github.com/dancannon/gorethink#WriteResponse) and does not require closing of any cursor?

**Comment by kofalt** [comment] 2015-07-22 17:31
After re-reading some earlier comments, I'm assuming both your and @nkev's examples meant to have `Run` not `RunWrite`.

**Comment by dancannon** [comment] 2015-07-22 17:54
Yep, `RunWrite` does not return a `Cursor`

**Comment by dancannon** [comment] 2015-08-04 17:40
@nkev are you still having this issue now? If so can we close this issue?

**Comment by dancannon** [comment] 2015-08-09 22:32
Closing this issue again, for anybody else wondering how the issue was fixed there were a couple of queries that were not always being closed. The safe solution is to ensure that anytime you run a query with `Run` you defer the closing of the connection.

**Closed as completed by dancannon** 2015-08-09 22:32 UTC
Labels: t:bug, p:high

**Comment by nkev** [comment] 2015-08-09 22:56
Sorry Daniel I got caught up in work. After the code refactoring we are going well so far. I will let you know if we have the issue again.
