### ISSUE TITLE
Change the way Cursor pays attention to ReadTimeout when used with Changes

### ISSUE THREAD

**Issue by definitelycarter** [rethinkdb/rethinkdb-go#318] opened 2016-04-21 20:37 UTC
When a cursor doesn't receive a change from a change feed within the specified `ReadTimeout` in `ConnectOpts`, the cursor is marked as invalid and closed.

Since a change feed isn't guaranteed to receive a response within a certain time-frame is it possible
- For the read timeout to be handled internally
- or provide a way for the consumer to ignore a read timeout

Otherwise, it gets messy needing to create a new ChangeFeed even though the underlying connection appears to still be usable.

**Comment by dancannon** [comment] 2016-05-02 13:22
Sorry for taking so long to look into this issue, unfortunately it is not that easy to fix without completely changing the API which I am not too keen on doing. What I would instead suggest is that you use a separate session for any changefeed queries. This is because the timeouts are configured when calling `Connect` and not when the query is executed.

**Comment by tve** [comment] 2016-05-07 00:38
yikes! While a separate session is an OK workaround, this does seem like an issue to me. The ideal solution IMHO would be for RethinkDB to send keep-alives and have the driver set the keepalive interval to 1/3rd of the ReadTimeout or something like that. Maybe worth a feature request into RethinkDB (at least I didn't see any keepalive option)?

**Comment by dancannon** [comment] 2016-05-07 12:43
There is a related issue (#317) regarding a change to the driver which removed `KeepAlive` by default, this change has been reverted in the `develop` branch and will be released soon. Regarding having the ability to override the `ConnectOpts` at query time I agree that this will be useful it is just a slightly bigger change than it seems so it may take some time to get working.

**Comment by dancannon** [comment] 2016-07-12 20:52
Closing this as I believe this issue was fixed when the keep alive regression was fixed. You should b able to use the same session for change feeds without any additional configuration.

**Closed as completed by dancannon** 2016-07-12 20:52 UTC
Labels: p:low, s:complete
