### ISSUE TITLE
Subsequent errors cause a crash

### ISSUE THREAD

**Issue by eliezedeck** [rethinkdb/rethinkdb-go#252] opened 2015-12-23 13:17 UTC
I have a weird error which got me investigating why it happened.

Please try this following code on a database called "management". Run it twice as the first one will create the table, and the second one will exhibit the crash.

``` go
package main

import (
    "log"

    r "github.com/dancannon/gorethink"
)

var s *r.Session

func main() {
    s, _ = r.Connect(r.ConnectOpts{
        Address:       "localhost:28015",
        Database:      "management",
        DiscoverHosts: true,
    })

    // This first call will work as expected... an error about the table already
    // existing will be shown
    createTable()

    // This second call will badly fail:
    //   panic: runtime error: invalid memory address or nil pointer dereference
    createTable()
}

func createTable() {
    _, err := r.TableCreate("patients").RunWrite(s)
    if err != nil {
        log.Println(err)
    } else {
        log.Println("Table created")
    }
}
```

Here is the error that is produced:

```
2015/12/23 16:08:57 gorethink: Table `management.patients` already exists. in: 
r.TableCreate("patients")
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x61e46]
```

It seems to me that 2 subsequent errors will trigger this. I have also tried with a `DBCreate()` operation which creates the database "management" that already exists, and the call to any `TableCreate()` on an existing table will crash afterwards.

**Comment by dancannon** [comment] 2015-12-23 13:19
Hey, this looks like it could possibly be a duplicate of #251. Could you please run `go get -u ./...` again and see if that fixes the issue. If not could you post the full stack trace. Thanks

**Comment by eliezedeck** [comment] 2015-12-23 13:22
Indeed, an update indeed fixed it. Cheers!

**Closed as completed** 2015-12-23 13:22 UTC
