### ISSUE TITLE
Cursor is nil when subscribing to changes with no error

### ISSUE THREAD

**Issue by gusavila92** [rethinkdb/rethinkdb-go#370] opened 2016-09-10 22:02 UTC
Hello.

I've been using GoRethink in a real-time system for three months and the performance is awesome. I'm very happy using this library to provide real-time updates to many mobile devices.

Although, sometimes the server dies because of a panic in Go and I was able to log this panic as follows.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x50bb16]

goroutine 325129 [running]:
panic(0x813860, 0xc82000a0d0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
gopkg.in/dancannon/gorethink%2ev2.(*Cursor).bufferNextResponse(0xc825f10370, 0x0, 0x0)
    /Users/gustavoavila/Documents/gocode/src/gopkg.in/dancannon/gorethink.v2/cursor.go:668 +0x266
gopkg.in/dancannon/gorethink%2ev2.(*Cursor).seekCursor(0xc825f10370, 0x100000001, 0x0, 0x0)
    /Users/gustavoavila/Documents/gocode/src/gopkg.in/dancannon/gorethink.v2/cursor.go:606 +0xe7
gopkg.in/dancannon/gorethink%2ev2.(*Cursor).nextLocked(0xc825f10370, 0x74b260, 0xc826f2adc8, 0x1, 0x44f0d0, 0x0, 0x0)
    /Users/gustavoavila/Documents/gocode/src/gopkg.in/dancannon/gorethink.v2/cursor.go:206 +0x3c
gopkg.in/dancannon/gorethink%2ev2.(*Cursor).Next(0xc825f10370, 0x74b260, 0xc826f2adc8, 0x882540)
    /Users/gustavoavila/Documents/gocode/src/gopkg.in/dancannon/gorethink.v2/cursor.go:189 +0xb0
murealtime/database.SubscribeToCouriersChangefeeds(0xc825f10370, 0xc847c913e0)
    /Users/gustavoavila/Documents/gocode/src/murealtime/database/cliente.go:51 +0x7d
created by murealtime/aplicacionmensajero.subscribeToCourierChangefeeds
    /Users/gustavoavila/Documents/gocode/src/murealtime/aplicacionmensajero/connections_handler.go:62 +0x9a4
```

This panic occurs because, for some reason, sometimes I try to subscribe for changes in RethinkDB and I get a nil cursor with no error. My code is this:

```
func subscribeToCourierChangefeeds(globalCourierID int, ch chan<- model.JSON) (*r.Cursor, error) {
    cursor, error := r.Table("couriers").
        GetAll(globalCourierID).
        Pluck("name", "rating", "photo_url", "is_vip", "city_id", "is_express", "is_delivery", "courier_type", "last_known_latitude", "last_known_longitude").
        Changes().Run(database.Session)
    if error != nil {
        log.Error.Println("Error al suscribirse a los changefeeds del mensajero en la aplicación de los mensajeros: " + error.Error())
        return nil, error
    }
    go database.SubscribeToCouriersChangefeeds(cursor, ch)
    return cursor, nil
}
```

As you can see, I always verify if any errors occurred and immediately I return the function with this error, but for some reason no error is triggered with a nil cursor. Then, when I try to call the function in the database package, a panic is triggered at the line `for cursor.Next(&change) {` and the server dies :(

```
func SubscribeToCouriersChangefeeds(cursor *r.Cursor, ch chan<- model.JSON) {
    var change map[string](map[string]interface{})
    for cursor.Next(&change) {
        if cursor.Err() != nil {
            log.Error.Println("Error construyendo el mensajero del changefeed: " + cursor.Err().Error())
            continue
        }

        newVal := change["new_val"]
        oldVal := change["old_val"]

        var courier model.Courier
        var error error
        var action string

        if newVal != nil && oldVal == nil {
            error = encoding.Decode(&courier, newVal)
            action = model.ActionCourierAdded

        } else if oldVal != nil && newVal == nil {
            error = encoding.Decode(&courier, oldVal)
            action = model.ActionCourierDeleted

        } else {
            error = encoding.Decode(&courier, newVal)
            action = model.ActionCourierChanged
        }

        if error != nil {
            log.Error.Println("Error decodificando los datos de los changefeeds del mensajero: " + error.Error())
            continue
        }

        responseJSON := model.JSON{Action: action, Data: courier}
        ch <- responseJSON
    }
}
```

I return the cursor in the first function because I need to close the cursor when is no longer needed. This is my code:

```
courierChangefeedsChannel := make(chan model.JSON)
    courierCursor, errorSubscribingCourierChangefeeds := subscribeToCourierChangefeeds(globalCourierID, courierChangefeedsChannel)
    if errorSubscribingCourierChangefeeds != nil {
        return
    }
    defer closeCursor(courierCursor)
```

I would appreciate any help because this system is already in production.
Thanks.

**Comment by dancannon** [comment] 2016-09-11 00:55
Hi @gusavila92, really sorry that you are having this issue 😞  I have tried to fix it a couple of times before but have never been able to replicate it reliably. Although looking back I don't seem to have merged my previous fix! Could you try building your application with the `hotfix/cursor-panic` branch and see if that resolves the issue?

Regarding reproducing the bug how often does the panic occur? Are you able to make it panic reliably or does it just happen after the application has been running for a while?

**Comment by gusavila92** [comment] 2016-09-11 01:23
Hi. I'll build a new app with the hotfix you mentioned. I hope this will fix the issue.

This is a big server and it dies once every three or two days, but this is the first time I log all the panics. I was just logging the "normal" errors. Maybe it died before for some other reasons, so I don't know whether it has to do with this error or not.

I'll get back to you if this error happens again with the hotfix.
Thanks.

**Comment by dancannon** [comment] 2016-09-20 21:22
@gusavila92 I have merged the hotfix to master with `v2.2.1`, could you let me know if your application is still panicking because of this bug?

**Comment by dancannon** [comment] 2016-09-20 21:22
@gusavila92 I have merged the hotfix to master with `v2.2.1`, could you let me know if your application is still panicking because of this bug?

**Comment by gusavila92** [comment] 2016-09-20 23:05
No, it isn't panicking anymore. I think the bug is fixed.
Thank you.

**Comment by dancannon** [comment] 2016-09-20 23:40
Ok great 🎉  I will now close the issue. Thanks for the help! 😄

**Closed as completed by dancannon** 2016-09-20 23:40 UTC
Labels: t:bug, p:high
