### ISSUE TITLE
session hangs after repeated queries

### ISSUE THREAD

**Issue by bryfry** [rethinkdb/rethinkdb-go#180] opened 2015-04-22 01:55 UTC
Running latest gorethink master and rethinkdb 2.0.1

Essentially the issue happens after a number of rethink queries like below.  This hang doesn't happen every query, sometimes it comes back instantly, and it seems to not present itself if the query is intermixed with other queries (i.e. not repeated).  I've found the most reliable way to reliably get the hang is to trigger the same query multiple times with the same requests.  The debugging I've done in my code shows this query getting called but never returning.

This also causes all future requests to the session to hang.

`r.Db(config.DbName).Table(config.TableName).GetAllByIndex("indexname", "value").Run(session)`
where session is initialized as:

```
session, err := r.Connect(r.ConnectOpts{
   Address:  config.RethinkAddress,
   Database: config.DbName,
   MaxIdle:  10,
   MaxOpen:  10,
 })
```

Right now this call is embedded inside my application but if I'll try to workup a POC to see if I can replicate the behavior. 

Here is a screenshot of the cluster performance testing the above query 9 times approx. every 1 sec.  Notice only 8 queries.
![screen shot 2015-04-21 at 10 07 23 pm](https://cloud.githubusercontent.com/assets/116113/7266113/ecb59658-e872-11e4-9b3a-6dbdad7a38dc.png)

Are there any ways to enable some debugging or logging from the gorethink driver side?  (Edit: I found `SetVerbose` but haven't seen any changes in the log output). 

I'm still not convinced I'm not just doing Something Wrong&trade;

**Comment by bryfry** [comment] 2015-04-22 23:52
With some more testing I found that if I increased the `MaxOpen` `ConnectOpt` the number of queries that it took to hang the session rose to the same level.  Setting the `Timeout` explicitly and/or raising the `MaxIdle` didn't seem to have any effect.

**Comment by dancannon** [comment] 2015-04-23 20:34
Hi @bryfry, I am not quite sure what is going on just yet and I haven't got much time to look into this today but I will try to figure it out over the weekend.

As soon as I know more I will get back to you.

**Comment by dancannon** [comment] 2015-04-23 20:50
After running some quick tests to see if I could replicate the issue (I couldn't unfortunately) I have some follow up questions to help narrow down the cause:
- What are you doing with the returned cursor, you may not be closing it which could explain the issue as the connection would be kept open and not returned to the pool?
- Are you running the queries in parallel?
- Is the issue limited to a single type of query?
- What do you mean by "doesnt hang every query"? Do you mean that different ReQL queries succeed/fail or that the exact same ReQL query will randomly fail but sometimes work?

**Comment by bryfry** [comment] 2015-04-24 01:13
- The specific use case I've been using to test with from above is then passed to an `err = res.One(&value)`.  I've never done any closing after a `Run`, `One`.  Should I be `res.Close()`ing?  That makes so much sense if so.
- Queries are being run in parallel and sharing the `Session`
- I think all of the Exec and RunWrite queries I do for setup run fine (many in sequence).

Is there any way to show all the open connections/cursors?

I'm definitely going to go try `Close` on all the things, right now.

**Comment by bryfry** [comment] 2015-04-24 01:36
![xx0ayd3](https://cloud.githubusercontent.com/assets/116113/7310818/b7c96764-ea00-11e4-946e-f7b7369f8471.jpg)

I have a bit more testing to do but I think that was the issue.

**Comment by dancannon** [comment] 2015-04-24 07:03
Which version of the driver are you using? There was an issue before where One was not closing the cursor (it should). https://github.com/dancannon/gorethink/commit/88f86119f03def0bc804073ffbc53addc46cbda4

If you are using the latest version then there is a bug that should definitely be fixed, that being said maybe always closing the cursor is probably also a good idea.

**Comment by bryfry** [comment] 2015-04-24 11:46
I'm running latest master (did go get update before opening this ticket) with rethinkdb 2.0.0 and 2.0.1 in test.

**Comment by dancannon** [comment] 2015-04-24 11:49
Ok well at least we have narrowed down the cause of the issue, I will try to fix the bug this evening.

**Comment by dancannon** [comment] 2015-05-01 19:25
Hi, sorry for the delay I have not been feeling so great over the last week and have been taking some time off.

I have still not managed to track down the issue and as far as I can tell calling `One` will always close the cursor (https://github.com/dancannon/gorethink/blob/master/cursor.go#L265). Would it be possible to see the code that is hanging?

**Comment by dancannon** [comment] 2015-05-14 22:23
Im going to close this for now, if anybody still has this issue feel free to reopen it.

**Closed as completed by dancannon** 2015-05-14 22:23 UTC
Labels: t:bug, t:performance, p:medium
