### ISSUE TITLE
panic on RunWrite or Exec

### ISSUE THREAD

**Issue by bryfry** [rethinkdb/rethinkdb-go#152] opened 2015-02-15 02:29 UTC
I'm getting this panic running the latest master and rethinkdb 1.15.3-1`

```
'2015/02/14 21:20:48 http: panic serving [::1]:58365: runtime error: slice bounds out of range
goroutine 21 [running]:
net/http.func·011()
        /usr/local/Cellar/go/1.3.1/libexec/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x54ce80, 0x8c8c2f)
        /usr/local/Cellar/go/1.3.1/libexec/src/pkg/runtime/panic.c:248 +0x18d
github.com/dancannon/gorethink.(*Connection).writeQuery(0xc20802a1c0, 0x5a, 0xc208174000, 0x19fd, 0x25ab, 0x0, 0x0)
        /Users/bryfry/gocode/src/github.com/dancannon/gorethink/connection_helper.go:74 +0x3bb
github.com/dancannon/gorethink.(*Connection).sendQuery(0xc20802a1c0, 0x1, 0x5a, 0xc2080fd400, 0xc2080f0330, 0x0, 0x0)
        /Users/bryfry/gocode/src/github.com/dancannon/gorethink/connection.go:156 +0x22d
github.com/dancannon/gorethink.(*Connection).Query(0xc20802a1c0, 0xc200000001, 0x5a, 0xc2080fd400, 0xc2080f0330, 0x4eb31, 0x8, 0x0, 0x0)
        /Users/bryfry/gocode/src/github.com/dancannon/gorethink/connection.go:114 +0x12d
github.com/dancannon/gorethink.(*Pool).exec(0xc208054000, 0x1, 0x0, 0xc2080fd400, 0xc2080f0330, 0x0, 0x0)
        /Users/bryfry/gocode/src/github.com/dancannon/gorethink/pool.go:482 +0x15a
github.com/dancannon/gorethink.(*Pool).Exec(0xc208054000, 0x1, 0x0, 0xc2080fd400, 0xc2080f0330, 0x0, 0x0)
        /Users/bryfry/gocode/src/github.com/dancannon/gorethink/pool.go:465 +0x8c
github.com/dancannon/gorethink.Term.Exec(0x5b67c0, 0x6, 0x3800000000, 0x0, 0x0, 0xc20811e990, 0x2, 0x2, 0xc2080f0270, 0xc20802a000, ...)
        /Users/bryfry/gocode/src/github.com/dancannon/gorethink/query.go:256 +0x109
main.(*LMSDbSession).CreateTest(0xc208030080, 0xc2080dbce0, 0x10, 0xc208118c00, 0x19, 0xc208118c20, 0x1c, 0x2, 0x0, 0x5a, ...)
        /Users/bryfry/gocode/src/github.com/bryfry/project/model-test.go:52 +0x486
```

The line in question is

`err = r.Db("testdb").Table("tests").Insert(t).Exec(db.Session)`
or
`res, err = r.Db("testdb").Table("tests").Insert(t).RunWrite(db.Session)`

I've verified that t has the expected values to be inserted.
This break occurred when I upgraded gorethink. So any help in how my code might need to change or be updated would be greatly appreciated!

**Comment by wangbin** [comment] 2015-02-15 09:25
I got the same error with latest master and rethinkdb-1.16.1, I manually change [connection_helper.go line 74](https://github.com/dancannon/gorethink/blob/master/connection_helper.go#L74) to:

```
data := c.buf.takeBuffer(dataLen)
```

my code is working now without any problems. I think the problem is I am inserting articles into db with content larger than defaultBufSize, bug takeSmallBuffer method didn't check the length, as did in takeBuffer method.

**Comment by dancannon** [comment] 2015-02-15 11:53
Thanks for letting me know, it was a bit of an oversight on my part.

Ill push a fix right away.

**Comment by dancannon** [comment] 2015-02-15 12:25
Closing as this should now be fixed. Let me know if you are still having issues.

**Closed as completed by dancannon** 2015-02-15 12:25 UTC
Labels: t:bug, p:high
