### ISSUE TITLE
Omit Empty on a String

### ISSUE THREAD

**Issue by ronniekritou** [rethinkdb/rethinkdb-go#260] opened 2016-01-15 18:21 UTC
In my situation when persisting to rethink, I have an empty string , and my rethink tag is omitempty, but it persists the empty string.

If possible can you have an empty string check in here as well ? You go through practically everything , i'm just not sure if you are purposely skipping it.

https://github.com/dancannon/gorethink/blob/master/encoding/utils.go#L20-L36

**Comment by dancannon** [comment] 2016-01-15 20:01
Hi I have to check the implementation but your request sounds reasonable. I am away on holiday for a week but will look into the change when I get back.

**Comment by dancannon** [comment] 2016-01-22 20:48
I checked the implementation and it looks like it is checking for an empty string. This [line](https://github.com/dancannon/gorethink/blob/master/encoding/utils.go#L23) checks if the length of the string is 0. There is also this [test case](https://github.com/dancannon/gorethink/blob/master/encoding/encoder_test.go#L70-L110) that checks that omitempty doesnt persist an empty string.

Could you provide a sample of some code that is persisting an empty string?

**Comment by dancannon** [comment] 2016-02-01 22:24
Closing as I cant reproduce this.

**Closed as completed by dancannon** 2016-02-01 22:24 UTC
Labels: t:enhancement, p:low
