### ISSUE TITLE
Testing Filter not working

### ISSUE THREAD

**Issue by kujtimiihoxha** [rethinkdb/rethinkdb-go#356] opened 2016-08-08 09:08 UTC
I am trying to test my app but ran into this problem.

``` go
mock := r.NewMock()
mock.On(r.Table("test").Filter(r.Row.Field("name").Eq("Kujtim Hoxha"))).Return([]interface{}{
    map[string]interface{}{"id": 4, "name": "Kujtim Hoxha"},
},nil)
cursor,_:=r.Table("test").Filter(r.Row.Field("name").Eq("Kujtim Hoxha")).Run(mock)
```

I get an error saying that the query was not expected.

It looks like the query when translated into string is turned into

```
r.Table("test").Filter(func(var_2 r.Term) r.Term { return r.Row.Field("name").Eq("Kujtim Hoxha") })
```

I suspect that in `mock.On` the query is translated to 

```
r.Table("test").Filter(func(var_1 r.Term) r.Term { return r.Row.Field("name").Eq("Kujtim Hoxha") })
```

So mock will not expect this query.

Is there a workaround for this ?

**Comment by dancannon** [comment] 2016-08-08 22:04
Hi, thanks for reporting this issue. I have been able to replicate the issue locally and have discovered that this is caused by the way the driver builds functions in ReQL, internally the driver contains a counter which is used to chose a unique identifier for all variables used in any functions.

Unfortunately because this counter is global a different ID is used when mocking the query and running the query. I will try to figure a better way of comparing the mocked function variables to the actual function variables and release this as part of v2.2.0 which will hopefully be coming in the next couple of weeks.

**Comment by dancannon** [comment] 2016-08-17 20:59
The fix has been released to master.

**Closed as completed by dancannon** 2016-08-17 20:59 UTC
Labels: t:bug, p:medium, s:complete
